### PR TITLE
Apply Geopipe patch for URL images.

### PR DESCRIPTION
**Pull request by flying-kestrel**
This passes any `http[s]://` URLs that are present in the source DAE through to the end GLTF; this is needed for [geopipe#1518](https://github.com/Geopipe/geopipe/pull/1518).

### CODE REVIEW

**Review by elfprince13 — CHANGES_REQUESTED** [review]
Could we put this behind a command-line flag? It would be nice to be able to still pack them in automatically if we want to.

**Comment by flying-kestrel** [comment]
This only allows relative URLs to be specified. COLLADA2GLTF seems like the wrong place to put the relevant code for packing into a single GLTF — that's model-specific logic and should go in `gen_merged_dae.py`, which in fact already handles this. :)

**Comment by elfprince13** [comment]
what I mean is - `COLLADA2GLTF` is a general purpose tool for turning collada models into GLTF models, and having the ability to create "self contained" GLTFs that can be redistributed without needing access to a particular http[s] server is useful to us and it would be annoying to have to keep two copies of the utility compiled just for that feature.

**Comment by flying-kestrel** [comment]
> what I mean is - COLLADA2GLTF is a general purpose tool for turning collada models into GLTF models, and having the ability to create "self contained" GLTFs that can be redistributed without needing access to a particular http[s] server is useful to us and it would be annoying to have to keep two copies of the utility compiled just for that feature.

I agree. However, the feature you mention is _not_ included in this PR. The source images are _not_ loaded, despite the _very_ misleading function name [`GLTF::Image::load`](https://github.com/Geopipe/COLLADA2GLTF/blob/d16ad76b476f4922b3281231f84338961f3506db/GLTF/src/GLTFImage.cpp#L44); if absolute URI mode is enabled, then the URI is simply written out without the image being loaded into the resulting GLTF/GLB as a blob.

**The _only_ support this patch includes is detecting if a URI is a URL and so should not be treated as a local filesystem path.** (bolded for emphasis)

**Comment by elfprince13** [comment]
understood!

**Review by elfprince13 — APPROVED** [review]

**Pull request merged**
